"""documents domain: uploads, visibility, contract acknowledgement

Revision ID: 0ab285bfbb27
Revises: 543ddc2dd944
Create Date: 2026-07-20 21:27:23.359010
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '0ab285bfbb27'
down_revision: str | None = '543ddc2dd944'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('owner_person_id', sa.String(length=64), nullable=False),
    sa.Column('subject_person_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.Enum('GENERAL', 'CONTRACT', name='documenttype', native_enum=False, length=40), nullable=False),
    sa.Column('visibility', sa.Enum('STAFF_ONLY', 'SUBJECT', name='documentvisibility', native_enum=False, length=40), nullable=False),
    sa.Column('retention_period', sa.Enum('ONE_YEAR', 'THREE_YEARS', 'FIVE_YEARS', 'TEN_YEARS', 'INDEFINITE', name='retentionperiod', native_enum=False, length=40), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_person_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_document_org_subject', 'document', ['organization_id', 'subject_person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_org_subject', table_name='document')
    op.drop_table('document')
    # ### end Alembic commands ###
