"""data import staging tables

Revision ID: 0cfcd81ee3fa
Revises: d6b76b77e632
Create Date: 2026-07-20 21:29:51.554838
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0cfcd81ee3fa'
down_revision: str | None = 'd6b76b77e632'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batch',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PREVIEWED', 'COMMITTED', name='importbatchstatus', native_enum=False, length=40), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('created_by_person_id', sa.String(length=64), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('created_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('committed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_row',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=False),
    sa.Column('family_name', sa.String(length=120), nullable=False),
    sa.Column('group_name', sa.String(length=160), nullable=True),
    sa.Column('local_member_code', sa.String(length=60), nullable=True),
    sa.Column('validation_status', sa.Enum('PENDING', 'VALID', 'INVALID', name='importrowvalidationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('validation_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_person_ids', postgresql.ARRAY(sa.String(length=64)), nullable=True),
    sa.Column('commit_status', sa.Enum('PENDING', 'CREATED', 'SKIPPED', name='importrowcommitstatus', native_enum=False, length=40), nullable=False),
    sa.Column('commit_reason', sa.Text(), nullable=True),
    sa.Column('created_person_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_row')
    op.drop_table('import_batch')
    # ### end Alembic commands ###
