"""organization membership, people, groups

Revision ID: 12baf1ac02ef
Revises: 1c9694b6e528
Create Date: 2026-07-17 00:37:13.804534
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '12baf1ac02ef'
down_revision: str | None = '1c9694b6e528'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_person_reference',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source', 'external_id', name='uq_external_person_ref')
    )
    op.create_table('group',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('capacity_mode', sa.Enum('UNLIMITED', 'LIMITED', name='groupcapacitymode', native_enum=False, length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardian_organization_access',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('guardian_person_id', sa.String(length=64), nullable=False),
    sa.Column('child_person_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', name='guardianaccessstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'guardian_person_id', 'child_person_id', name='uq_guardian_org_access')
    )
    op.create_table('guardian_relationship',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('guardian_person_id', sa.String(length=64), nullable=False),
    sa.Column('child_person_id', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.Enum('PARENT', 'LEGAL_GUARDIAN', 'OTHER', name='guardianrelationshiptype', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guardian_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_person_id', 'child_person_id', name='uq_guardian_relationship')
    )
    op.create_table('organization_membership',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='membershipstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'person_id', name='uq_org_membership')
    )
    op.create_table('group_membership',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('group_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_reason', sa.Enum('LEFT', 'MOVED', 'REMOVED', 'SEASON_END', name='groupmembershipendreason', native_enum=False, length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'person_id', name='uq_group_membership')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_membership')
    op.drop_table('organization_membership')
    op.drop_table('guardian_relationship')
    op.drop_table('guardian_organization_access')
    op.drop_table('group')
    op.drop_table('external_person_reference')
    # ### end Alembic commands ###
