"""billing and payments

Revision ID: 1c308cdafeb8
Revises: 0fc97b619ac6
Create Date: 2026-07-17 00:48:32.365767
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c308cdafeb8'
down_revision: str | None = '0fc97b619ac6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_run',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('period_label', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'CANCELLED', name='billingrunstatus', native_enum=False, length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_minor', sa.Integer(), nullable=False),
    sa.Column('charge_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charge',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('billing_run_id', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.Enum('MEMBERSHIP', 'EVENT', 'MANUAL', 'OTHER', name='chargesourcetype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', name='chargestatus', native_enum=False, length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount_due_minor', sa.Integer(), nullable=False),
    sa.Column('amount_paid_minor', sa.Integer(), nullable=False),
    sa.Column('cancellation_reason', sa.Enum('WAIVED', 'ERROR', 'DUPLICATE', 'OTHER', name='chargecancellationreasoncode', native_enum=False, length=40), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_run_id'], ['billing_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_record',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('charge_id', sa.String(length=64), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.Enum('CASH', 'BANK_TRANSFER', 'CARD_EXTERNAL', 'OTHER', name='paymentmethod', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('RECORDED', 'VOIDED', name='paymentrecordstatus', native_enum=False, length=40), nullable=False),
    sa.Column('void_reason', sa.Enum('ERROR', 'REFUNDED', 'DUPLICATE', 'OTHER', name='paymentvoidreasoncode', native_enum=False, length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['charge_id'], ['charge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_record')
    op.drop_table('charge')
    op.drop_table('billing_run')
    # ### end Alembic commands ###
