"""identity, roles, organization

Revision ID: 1c9694b6e528
Revises: 3c1d76e1c83a
Create Date: 2026-07-17 00:28:17.341845
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1c9694b6e528'
down_revision: str | None = '3c1d76e1c83a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('SCHOOL', 'SPORTS_CLUB', 'DANCE_SCHOOL', 'COURSE_PROVIDER', 'EVENT_ORGANIZER', 'BUSINESS', 'OTHER', name='organizationtype', native_enum=False, length=40), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('given_name', sa.String(length=120), nullable=False),
    sa.Column('family_name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=240), nullable=False),
    sa.Column('identity_status', sa.Enum('PROVISIONAL', 'CLAIMED', 'VERIFIED', 'MERGED', 'ARCHIVED', name='personidentitystatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_merge_record',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_person_id', sa.String(length=64), nullable=False),
    sa.Column('target_person_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('performed_by_person_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_person_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_account',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='authaccountstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('invitation',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('STAFF', 'PARENT', 'STUDENT', name='invitationtype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', 'REISSUED', name='invitationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=True),
    sa.Column('target_email', sa.String(length=320), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_assignment',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('role_code', sa.Enum('OWNER', 'MANAGER', 'ADMIN', 'TRAINER', 'PARENT', 'STUDENT', name='rolecode', native_enum=False, length=40), nullable=False),
    sa.Column('scope_type', sa.Enum('ORGANIZATION', 'BRANCH', 'GROUP', name='rolescopetype', native_enum=False, length=40), nullable=False),
    sa.Column('scope_ref_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'REVOKED', name='roleassignmentstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'organization_id', 'role_code', 'scope_type', 'scope_ref_id', name='uq_role_assignment')
    )
    op.create_table('student_login_authorization',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('student_person_id', sa.String(length=64), nullable=False),
    sa.Column('login_enabled', sa.Boolean(), nullable=False),
    sa.Column('authorized_by_person_id', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_person_id')
    )
    op.create_table('auth_identifier',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('auth_account_id', sa.String(length=64), nullable=False),
    sa.Column('type', sa.Enum('SUBJECT', 'EMAIL', 'PHONE', name='authidentifiertype', native_enum=False, length=40), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auth_account_id'], ['auth_account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_auth_identifier')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_identifier')
    op.drop_table('student_login_authorization')
    op.drop_table('role_assignment')
    op.drop_table('invitation')
    op.drop_table('auth_account')
    op.drop_table('workspace')
    op.drop_table('person_merge_record')
    op.drop_table('person')
    op.drop_table('organization')
    # ### end Alembic commands ###
