"""structure sub-entities: category, program, location, room

Revision ID: 2d0e95a75ed8
Revises: 41f45ac4b0ee
Create Date: 2026-07-20 19:57:09.304653
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2d0e95a75ed8'
down_revision: str | None = '41f45ac4b0ee'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_category',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structure_category_org', 'structure_category', ['organization_id'], unique=False)
    op.create_table('structure_location',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('internal_code', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structure_location_org', 'structure_location', ['organization_id'], unique=False)
    op.create_index('ix_structure_location_org_code', 'structure_location', ['organization_id', 'internal_code'], unique=False)
    op.create_table('structure_program',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('internal_code', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['structure_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structure_program_org', 'structure_program', ['organization_id'], unique=False)
    op.create_index('ix_structure_program_org_code', 'structure_program', ['organization_id', 'internal_code'], unique=False)
    op.create_table('structure_room',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('location_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('internal_code', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['structure_location.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_structure_room_org', 'structure_room', ['organization_id'], unique=False)
    op.create_index('ix_structure_room_org_code', 'structure_room', ['organization_id', 'internal_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_structure_room_org_code', table_name='structure_room')
    op.drop_index('ix_structure_room_org', table_name='structure_room')
    op.drop_table('structure_room')
    op.drop_index('ix_structure_program_org_code', table_name='structure_program')
    op.drop_index('ix_structure_program_org', table_name='structure_program')
    op.drop_table('structure_program')
    op.drop_index('ix_structure_location_org_code', table_name='structure_location')
    op.drop_index('ix_structure_location_org', table_name='structure_location')
    op.drop_table('structure_location')
    op.drop_index('ix_structure_category_org', table_name='structure_category')
    op.drop_table('structure_category')
    # ### end Alembic commands ###
