"""session series recurrence fields and trainer

Revision ID: 3fed03b597f7
Revises: 2d0e95a75ed8
Create Date: 2026-07-20 20:05:58.081882
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3fed03b597f7'
down_revision: str | None = '2d0e95a75ed8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('trainer_person_id', sa.String(length=64), nullable=True))
    op.create_foreign_key(
        'fk_session_trainer_person_id', 'session', 'person',
        ['trainer_person_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('session_series', sa.Column('trainer_person_id', sa.String(length=64), nullable=True))
    # New non-null columns; session_series had no create path before this migration,
    # so the table is empty and the backfill defaults are only a safety net.
    op.add_column(
        'session_series',
        sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()),
                  nullable=False, server_default=sa.text("'[]'::jsonb")),
    )
    op.add_column(
        'session_series',
        sa.Column('start_date', sa.Date(), nullable=False,
                  server_default=sa.text('CURRENT_DATE')),
    )
    op.alter_column('session_series', 'weekdays', server_default=None)
    op.alter_column('session_series', 'start_date', server_default=None)
    op.create_foreign_key(
        'fk_session_series_trainer_person_id', 'session_series', 'person',
        ['trainer_person_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_session_series_trainer_person_id', 'session_series', type_='foreignkey')
    op.drop_column('session_series', 'start_date')
    op.drop_column('session_series', 'weekdays')
    op.drop_column('session_series', 'trainer_person_id')
    op.drop_constraint('fk_session_trainer_person_id', 'session', type_='foreignkey')
    op.drop_column('session', 'trainer_person_id')
    # ### end Alembic commands ###
