"""role assignment granted areas

Revision ID: 41f45ac4b0ee
Revises: 4f3c0bbeb6de
Create Date: 2026-07-20 19:58:27.616205
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '41f45ac4b0ee'
down_revision: str | None = '4f3c0bbeb6de'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_assignment', sa.Column('granted_areas', postgresql.ARRAY(sa.String(length=40)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_assignment', 'granted_areas')
    # ### end Alembic commands ###
