"""organization slug for tenant login

Revision ID: 4f3c0bbeb6de
Revises: 6119a4b1ab5c
Create Date: 2026-07-17 01:44:56.017102
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4f3c0bbeb6de'
down_revision: str | None = '6119a4b1ab5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('slug', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'organization', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization', type_='unique')
    op.drop_column('organization', 'slug')
    # ### end Alembic commands ###
