"""onboarding progress and organization lifecycle status

Revision ID: 543ddc2dd944
Revises: 83eee9b8c108
Create Date: 2026-07-20 21:27:52.407511
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '543ddc2dd944'
down_revision: str | None = '83eee9b8c108'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_progress',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    # Backfill existing rows to ACTIVE (legacy schools behave normally, unchanged
    # by guided onboarding), then drop the server default so the column matches
    # the model (Python-side default; only ``create_organization`` opts a fresh
    # school into IN_PREPARATION explicitly).
    op.add_column(
        'organization',
        sa.Column(
            'lifecycle_status',
            sa.Enum('IN_PREPARATION', 'ACTIVE', name='organizationlifecyclestatus',
                    native_enum=False, length=40),
            nullable=False, server_default=sa.text("'ACTIVE'"),
        ),
    )
    op.alter_column('organization', 'lifecycle_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'lifecycle_status')
    op.drop_table('onboarding_progress')
    # ### end Alembic commands ###
