"""events and communications

Revision ID: 6119a4b1ab5c
Revises: 1c308cdafeb8
Create Date: 2026-07-17 00:53:50.500232
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6119a4b1ab5c'
down_revision: str | None = '1c308cdafeb8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Enum('ORGANIZATION', 'GROUP', name='announcementtargettype', native_enum=False, length=40), nullable=False),
    sa.Column('target_group_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='announcementstatus', native_enum=False, length=40), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('TRAINING_CAMP', 'COMPETITION', 'WORKSHOP', 'SOCIAL', 'OTHER', name='eventtype', native_enum=False, length=40), nullable=False),
    sa.Column('category', sa.Enum('INTERNAL', 'EXTERNAL', name='eventcategory', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', name='eventstatus', native_enum=False, length=40), nullable=False),
    sa.Column('capacity_mode', sa.Enum('UNLIMITED', 'LIMITED', name='eventcapacitymode', native_enum=False, length=40), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_recipient',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('announcement_id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_registration',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('child_person_id', sa.String(length=64), nullable=False),
    sa.Column('registered_by_person_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'CANCELLED', name='registrationstatus', native_enum=False, length=40), nullable=False),
    sa.Column('cancellation_reason', sa.Enum('PARENT_REQUEST', 'ORGANIZER', 'OTHER', name='cancellationreasoncode', native_enum=False, length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['child_person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'child_person_id', name='uq_event_registration')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_registration')
    op.drop_table('announcement_recipient')
    op.drop_table('event')
    op.drop_table('announcement')
    # ### end Alembic commands ###
