"""invitation role assignment fields

Revision ID: 83eee9b8c108
Revises: bb71ff179332
Create Date: 2026-07-20 20:51:15.486847
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '83eee9b8c108'
down_revision: str | None = 'bb71ff179332'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitation', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invitation', sa.Column('role_code', sa.Enum('OWNER', 'MANAGER', 'ADMIN', 'TRAINER', 'PARENT', 'STUDENT', name='rolecode', native_enum=False, length=40), nullable=False))
    op.add_column('invitation', sa.Column('scope_type', sa.Enum('ORGANIZATION', 'BRANCH', 'GROUP', name='rolescopetype', native_enum=False, length=40), nullable=False))
    op.add_column('invitation', sa.Column('scope_ref_id', sa.String(length=64), nullable=True))
    op.add_column('invitation', sa.Column('granted_areas', postgresql.ARRAY(sa.String(length=40)), nullable=True))
    op.add_column('invitation', sa.Column('target_child_person_id', sa.String(length=64), nullable=True))
    op.add_column('invitation', sa.Column('invited_by_person_id', sa.String(length=64), nullable=True))
    op.add_column('invitation', sa.Column('reissued_from_invitation_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_invitation_token_hash', 'invitation', ['token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_invitation_token_hash', 'invitation', type_='unique')
    op.drop_column('invitation', 'reissued_from_invitation_id')
    op.drop_column('invitation', 'invited_by_person_id')
    op.drop_column('invitation', 'target_child_person_id')
    op.drop_column('invitation', 'granted_areas')
    op.drop_column('invitation', 'scope_ref_id')
    op.drop_column('invitation', 'scope_type')
    op.drop_column('invitation', 'role_code')
    op.drop_column('invitation', 'accepted_at')
    # ### end Alembic commands ###
