"""privacy domain: consents, dsar requests, retention periods

Revision ID: d3d1b0e93328
Revises: 83eee9b8c108
Create Date: 2026-07-20 21:28:11.557214
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd3d1b0e93328'
down_revision: str | None = '83eee9b8c108'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privacy_consent_record',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.Enum('DATA_PROCESSING', 'MARKETING_COMMUNICATIONS', 'PHOTO_VIDEO', 'THIRD_PARTY_SHARING', name='consentscope', native_enum=False, length=40), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_person_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_privacy_consent_record_org_person', 'privacy_consent_record', ['organization_id', 'person_id'], unique=False)
    op.create_table('privacy_data_subject_request',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('person_id', sa.String(length=64), nullable=False),
    sa.Column('request_type', sa.Enum('ACCESS', 'EXPORT', 'ERASURE', name='dsarrequesttype', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'FULFILLED', 'REJECTED', name='dsarrequeststatus', native_enum=False, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('requested_by_person_id', sa.String(length=64), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_by_person_id', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_privacy_dsar_org_person', 'privacy_data_subject_request', ['organization_id', 'person_id'], unique=False)
    op.create_table('privacy_retention_period',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.String(length=64), nullable=False),
    sa.Column('data_category', sa.Enum('PERSONAL_PROFILE', 'ATTENDANCE_RECORDS', 'BILLING_RECORDS', 'DOCUMENTS', 'COMMUNICATIONS', 'MEDIA', name='datacategory', native_enum=False, length=40), nullable=False),
    sa.Column('retention_period_days', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('record_status', sa.Enum('ACTIVE', 'ARCHIVED', name='recordstatus', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_privacy_retention_period_org', 'privacy_retention_period', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_privacy_retention_period_org', table_name='privacy_retention_period')
    op.drop_table('privacy_retention_period')
    op.drop_index('ix_privacy_dsar_org_person', table_name='privacy_data_subject_request')
    op.drop_table('privacy_data_subject_request')
    op.drop_index('ix_privacy_consent_record_org_person', table_name='privacy_consent_record')
    op.drop_table('privacy_consent_record')
    # ### end Alembic commands ###
