"""M05 authorization policy registry

M05 §2.2–2.4. The catalogue of what permissions exist, what a role key means
and which roles hold which permissions.

Reference data, not tenant data: none of these tables carries a `school_id`.
A permission catalogue is the same catalogue for every school, and a tenant
column would invite per-school policy, which §3.2 point 3 rules out — a new
permission is default-deny for every role until a published revision says
otherwise. What a *person* holds stays in `role_assignment`, which already
exists; this says what the role key they hold actually means.

Two invariants go into the database rather than into application care:

* **Exactly one ACTIVE revision** (§2.2), as a partial unique index on
  `status`. "Exactly one" survives precisely as long as nobody writes a second
  code path, so it is not left to one.
* **HIGH and CRITICAL permissions always require step-up** (§2.3), as a CHECK.
  A registry row claiming a CRITICAL permission needs no step-up would
  silently disable it for every caller, and nothing else would notice.

The composite foreign keys all carry `policy_revision_id`, so a binding cannot
reach across revisions to a role or permission that a later revision changed —
the same idea M03 §7.3 applies to tenants, applied here to revisions.

`authorization_domain_key` is a string, not a database enum. §2.2.1 says in so
many words that the store must not use a closed `SCHOOL|PLATFORM` enum needing
existing rows rewritten to add a domain safely: a new domain arrives as a row
in a new revision, never as a schema change.

This migration creates the tables only. Seeding revision 1.3 and the resolver
that reads it are the next slice, so that a seed of ~40 permission rows is
reviewed as data rather than buried in a schema change.

Revision ID: f9bcbb4ddfb1
Revises: d4b83c17e5f9
Create Date: 2026-09-19 17:50:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f9bcbb4ddfb1'
down_revision: str | None = 'd4b83c17e5f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_policy_revision',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'SUPERSEDED', 'REJECTED', name='policyrevisionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('canonical_content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_account_id', sa.String(length=64), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_by_account_id', sa.String(length=64), nullable=True),
    sa.Column('change_reason_code', sa.Enum('INITIAL_PUBLICATION', 'PERMISSION_ADDED', 'BINDING_CHANGED', 'SECURITY_CORRECTION', 'MODULE_ONBOARDING', name='policychangereason', native_enum=False, length=40), nullable=False),
    sa.Column('change_ticket_ref', sa.String(length=100), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revision_no', name='uq_policy_revision_no')
    )
    op.create_index('uq_policy_revision_single_active', 'authorization_policy_revision', ['status'], unique=True, postgresql_where="status = 'ACTIVE'")
    op.create_table('authorization_domain_definition',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('policy_revision_id', sa.String(length=64), nullable=False),
    sa.Column('authorization_domain_key', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RESERVED', 'RETIRED', name='authorizationdomainstatus', native_enum=False, length=40), nullable=False),
    sa.Column('owner_module_id', sa.String(length=8), nullable=False),
    sa.Column('context_resolver_key', sa.String(length=120), nullable=False),
    sa.Column('requires_subject_guard', sa.Boolean(), nullable=False),
    sa.Column('is_organization_contract_scope', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_revision_id'], ['authorization_policy_revision.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_revision_id', 'authorization_domain_key', name='uq_authorization_domain_per_revision')
    )
    op.create_table('permission_definition',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('policy_revision_id', sa.String(length=64), nullable=False),
    sa.Column('permission_key', sa.String(length=120), nullable=False),
    sa.Column('authorization_domain_key', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'ELEVATED', 'HIGH', 'CRITICAL', name='risklevel', native_enum=False, length=40), nullable=False),
    sa.Column('delegation_class', sa.Enum('ROLE_ONLY', 'DIRECT_DELEGABLE', 'INTERNAL_ONLY', 'NON_DELEGABLE', name='delegationclass', native_enum=False, length=40), nullable=False),
    sa.Column('step_up_required', sa.Boolean(), nullable=False),
    sa.Column('offline_policy', sa.Enum('DENY', 'READ_CACHE_ALLOWED', 'QUEUE_ALLOWED', name='offlinepolicy', native_enum=False, length=40), nullable=False),
    sa.Column('child_data_class', sa.Enum('NONE', 'IDENTIFIER_ONLY', 'ROSTER_MINIMAL', 'STANDARD_CHILD', 'SPECIAL_CATEGORY', name='childdataclass', native_enum=False, length=40), nullable=False),
    sa.Column('subject_guard_key', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RETIRED', name='permissionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level NOT IN ('HIGH', 'CRITICAL') OR step_up_required", name='ck_permission_step_up_for_high_risk'),
    sa.ForeignKeyConstraint(['policy_revision_id', 'authorization_domain_key'], ['authorization_domain_definition.policy_revision_id', 'authorization_domain_definition.authorization_domain_key'], name='fk_permission_domain_in_revision', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_revision_id', 'permission_key', name='uq_permission_per_revision')
    )
    op.create_table('role_definition',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('policy_revision_id', sa.String(length=64), nullable=False),
    sa.Column('role_key', sa.String(length=64), nullable=False),
    sa.Column('authorization_domain_key', sa.String(length=64), nullable=False),
    sa.Column('workspace_key', sa.String(length=64), nullable=True),
    sa.Column('localization_key', sa.String(length=120), nullable=False),
    sa.Column('administrative_rank', sa.SmallInteger(), nullable=False),
    sa.Column('assignment_policy', sa.Enum('M04_M02_ONLY', 'OWNER_MANAGED', 'OWNER_OR_MANAGER_MANAGED', 'M07_ONLY', 'PLATFORM_SECURITY_MANAGED', 'OWNER_MODULE_MANAGED', name='assignmentpolicy', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'RETIRED', name='roledefinitionstatus', native_enum=False, length=40), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_revision_id', 'authorization_domain_key'], ['authorization_domain_definition.policy_revision_id', 'authorization_domain_definition.authorization_domain_key'], name='fk_role_domain_in_revision', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_revision_id', 'authorization_domain_key', 'role_key', name='uq_role_definition_per_revision')
    )
    op.create_table('role_permission_binding',
    sa.Column('policy_revision_id', sa.String(length=64), nullable=False),
    sa.Column('role_key', sa.String(length=64), nullable=False),
    sa.Column('permission_key', sa.String(length=120), nullable=False),
    sa.Column('authorization_domain_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_revision_id', 'authorization_domain_key', 'role_key'], ['role_definition.policy_revision_id', 'role_definition.authorization_domain_key', 'role_definition.role_key'], name='fk_binding_role_in_revision', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_revision_id', 'permission_key'], ['permission_definition.policy_revision_id', 'permission_definition.permission_key'], name='fk_binding_permission_in_revision', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_revision_id', 'role_key', 'permission_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permission_binding')
    op.drop_table('role_definition')
    op.drop_table('permission_definition')
    op.drop_table('authorization_domain_definition')
    op.drop_index('uq_policy_revision_single_active', table_name='authorization_policy_revision', postgresql_where="status = 'ACTIVE'")
    op.drop_table('authorization_policy_revision')
    # ### end Alembic commands ###
