/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auth Config
         * @description Tell the frontend which sign-in methods are available.
         */
        get: operations["authConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Callback */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google Login */
        get: operations["googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Billing Run */
        post: operations["postBillingRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/runs/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Billing Run */
        post: operations["previewBillingRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Charges */
        get: operations["listCharges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/charges/{charge_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Payment */
        post: operations["recordPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communications/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Announcement */
        post: operations["publishAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/communications/announcements/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Announcement */
        post: operations["previewAnnouncement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["listEvents"];
        put?: never;
        /** Create Event */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Children */
        post: operations["registerChildren"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{event_id}/registrations/{registration_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Registration */
        post: operations["cancelRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Groups */
        get: operations["listGroups"];
        put?: never;
        /** Create Group */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Group Members */
        get: operations["listGroupMembers"];
        put?: never;
        /** Add Group Member */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["healthLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["healthReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/dev/identities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Dev Identity */
        post: operations["createDevIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description The authenticated person and the contexts they may act in. Called before a
         *     context is chosen, so it requires authentication but no active context.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Contexts */
        get: operations["listMyContexts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Organization
         * @description Create a new organization. The caller becomes its owner. Requires
         *     authentication but no prior context (this is how a tenant is bootstrapped).
         */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Current Organization */
        get: operations["getCurrentOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parent/children": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Children */
        get: operations["listMyChildren"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List People */
        get: operations["listPeople"];
        put?: never;
        /** Create Person */
        post: operations["createPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Duplicate People */
        get: operations["listDuplicatePeople"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/merge-reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Merge Reviews */
        get: operations["listMergeReviews"];
        put?: never;
        /** Create Merge Review */
        post: operations["createMergeReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/merge-reviews/{review_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Merge Review */
        post: operations["decideMergeReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Person */
        get: operations["getPerson"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/guardians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Guardians */
        get: operations["listGuardians"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/guardians/{guardian_person_id}/primary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Primary Contact */
        post: operations["setPrimaryContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/guardians/{guardian_person_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke Guardian Access */
        post: operations["revokeGuardianAccess"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Membership */
        get: operations["getMembership"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Member Data */
        patch: operations["updateMemberData"];
        trace?: never;
    };
    "/people/{person_id}/membership/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Membership */
        post: operations["endMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/membership/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Membership */
        post: operations["resumeMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/{person_id}/membership/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suspend Membership */
        post: operations["suspendMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/conflict-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Conflict Check */
        post: operations["checkSessionConflicts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Schedule */
        get: operations["listSchedule"];
        put?: never;
        /** Create Session */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/sessions/{session_id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attendance */
        get: operations["getAttendanceSheet"];
        /** Save Attendance */
        put: operations["saveAttendance"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lookup Tenant
         * @description Public tenant discovery: map a school code to the tenant to log in to.
         */
        get: operations["lookupTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddGroupMemberRequest */
        AddGroupMemberRequest: {
            /** Person Id */
            person_id: string;
        };
        /** AnnouncementDraft */
        AnnouncementDraft: {
            /** Body */
            body: string;
            /** Target Group Id */
            target_group_id?: string | null;
            target_type: components["schemas"]["AnnouncementTargetType"];
            /** Title */
            title: string;
        };
        /** AnnouncementPreviewResponse */
        AnnouncementPreviewResponse: {
            /** Recipient Count */
            recipient_count: number;
            /** Snapshot Hash */
            snapshot_hash: string;
        };
        /** AnnouncementResponse */
        AnnouncementResponse: {
            /** Id */
            id: string;
            /** Recipient Count */
            recipient_count: number;
            status: components["schemas"]["AnnouncementStatus"];
            /** Title */
            title: string;
        };
        /**
         * AnnouncementStatus
         * @enum {string}
         */
        AnnouncementStatus: "DRAFT" | "PUBLISHED";
        /**
         * AnnouncementTargetType
         * @enum {string}
         */
        AnnouncementTargetType: "ORGANIZATION" | "GROUP";
        /** AttendanceEntry */
        AttendanceEntry: {
            /** Display Name */
            display_name: string;
            /** Person Id */
            person_id: string;
            status: components["schemas"]["AttendanceStatus"];
        };
        /** AttendanceException */
        AttendanceException: {
            override_reason?: components["schemas"]["AttendanceOverrideReasonCode"] | null;
            /** Person Id */
            person_id: string;
            status: components["schemas"]["AttendanceStatus"];
        };
        /**
         * AttendanceOverrideReasonCode
         * @enum {string}
         */
        AttendanceOverrideReasonCode: "LATE_ARRIVAL" | "EARLY_LEAVE" | "EXCUSED_ABSENCE" | "OTHER";
        /**
         * AttendanceSheet
         * @description The roster to display. Everyone defaults to PRESENT; the trainer edits only
         *     exceptions. ``attendance_version`` must be echoed back on save.
         */
        AttendanceSheet: {
            /** Attendance Version */
            attendance_version: number;
            /** Entries */
            entries: components["schemas"]["AttendanceEntry"][];
            /** Session Id */
            session_id: string;
        };
        /**
         * AttendanceStatus
         * @enum {string}
         */
        AttendanceStatus: "PRESENT" | "ABSENT" | "EXCUSED" | "LATE";
        /** AuthConfig */
        AuthConfig: {
            /** Dev Auth Enabled */
            dev_auth_enabled: boolean;
            /** Google Enabled */
            google_enabled: boolean;
        };
        /** BillingPreviewItem */
        BillingPreviewItem: {
            /** Amount Minor */
            amount_minor: number;
            /** Display Name */
            display_name: string;
            /** Person Id */
            person_id: string;
        };
        /** BillingPreviewRequest */
        BillingPreviewRequest: {
            /** Amount Minor */
            amount_minor: number;
            /** Description */
            description: string;
            /** Group Id */
            group_id: string;
            /** Period Label */
            period_label: string;
        };
        /** BillingPreviewResponse */
        BillingPreviewResponse: {
            /** Currency */
            currency: string;
            /** Items */
            items: components["schemas"]["BillingPreviewItem"][];
            /** Preview Hash */
            preview_hash: string;
            /** Total Minor */
            total_minor: number;
        };
        /** BillingRunResponse */
        BillingRunResponse: {
            /** Charge Count */
            charge_count: number;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Period Label */
            period_label: string;
            /** Total Minor */
            total_minor: number;
        };
        /** ChargeResponse */
        ChargeResponse: {
            /** Amount Due Minor */
            amount_due_minor: number;
            /** Amount Paid Minor */
            amount_paid_minor: number;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Person Id */
            person_id: string;
            status: components["schemas"]["ChargeStatus"];
        };
        /**
         * ChargeStatus
         * @enum {string}
         */
        ChargeStatus: "OPEN" | "PARTIALLY_PAID" | "PAID" | "CANCELLED";
        /** ChildSummary */
        ChildSummary: {
            /** Display Name */
            display_name: string;
            /** Person Id */
            person_id: string;
        };
        /** ConflictCheckResponse */
        ConflictCheckResponse: {
            /** Conflicts */
            conflicts: components["schemas"]["SessionSummary"][];
            /** Has Conflict */
            has_conflict: boolean;
        };
        /**
         * ContextSummary
         * @description One selectable acting context = an active role in one organization.
         */
        ContextSummary: {
            /** Organization Id */
            organization_id: string;
            /** Organization Name */
            organization_name: string;
            /** Role Assignment Id */
            role_assignment_id: string;
            role_code: components["schemas"]["RoleCode"];
            /** Scope Ref Id */
            scope_ref_id: string | null;
            scope_type: components["schemas"]["RoleScopeType"];
        };
        /** CreateDevIdentityRequest */
        CreateDevIdentityRequest: {
            /** Family Name */
            family_name: string;
            /** Given Name */
            given_name: string;
        };
        /** CreateEventRequest */
        CreateEventRequest: {
            /** Capacity */
            capacity?: number | null;
            /** @default UNLIMITED */
            capacity_mode: components["schemas"]["EventCapacityMode"];
            /** @default INTERNAL */
            category: components["schemas"]["EventCategory"];
            /** Ends At */
            ends_at?: string | null;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Title */
            title: string;
            /** @default OTHER */
            type: components["schemas"]["EventType"];
        };
        /** CreateGroupRequest */
        CreateGroupRequest: {
            /** Capacity */
            capacity?: number | null;
            /** @default UNLIMITED */
            capacity_mode: components["schemas"]["GroupCapacityMode"];
            /** Name */
            name: string;
        };
        /** CreateMergeReviewRequest */
        CreateMergeReviewRequest: {
            /** Reason */
            reason: string;
            /** Source Person Id */
            source_person_id: string;
            /** Target Person Id */
            target_person_id: string;
        };
        /** CreateOrganizationRequest */
        CreateOrganizationRequest: {
            /** Name */
            name: string;
            /**
             * Timezone
             * @default Europe/Belgrade
             */
            timezone: string;
            /** @default OTHER */
            type: components["schemas"]["OrganizationType"];
        };
        /** CreatePersonRequest */
        CreatePersonRequest: {
            /**
             * Allow Possible Duplicate
             * @default false
             */
            allow_possible_duplicate: boolean;
            /** Duplicate Reason */
            duplicate_reason?: string | null;
            /** Family Name */
            family_name: string;
            /** Given Name */
            given_name: string;
        };
        /** DevIdentityResponse */
        DevIdentityResponse: {
            /** Display Name */
            display_name: string;
            /** Person Id */
            person_id: string;
        };
        /** DuplicateCandidate */
        DuplicateCandidate: {
            /** Display Name */
            display_name: string;
            /** Person Id */
            person_id: string;
        };
        /** DuplicateCluster */
        DuplicateCluster: {
            /** Candidates */
            candidates: components["schemas"]["DuplicateCandidate"][];
            /** Family Name */
            family_name: string;
            /** Given Name */
            given_name: string;
        };
        /**
         * EventCapacityMode
         * @enum {string}
         */
        EventCapacityMode: "UNLIMITED" | "LIMITED";
        /**
         * EventCategory
         * @enum {string}
         */
        EventCategory: "INTERNAL" | "EXTERNAL";
        /** EventResponse */
        EventResponse: {
            /** Capacity */
            capacity: number | null;
            capacity_mode: components["schemas"]["EventCapacityMode"];
            category: components["schemas"]["EventCategory"];
            /** Id */
            id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            status: components["schemas"]["EventStatus"];
            /** Title */
            title: string;
            type: components["schemas"]["EventType"];
        };
        /**
         * EventStatus
         * @enum {string}
         */
        EventStatus: "DRAFT" | "PUBLISHED" | "CANCELLED" | "COMPLETED";
        /**
         * EventType
         * @enum {string}
         */
        EventType: "TRAINING_CAMP" | "COMPETITION" | "WORKSHOP" | "SOCIAL" | "OTHER";
        /**
         * GroupCapacityMode
         * @enum {string}
         */
        GroupCapacityMode: "UNLIMITED" | "LIMITED";
        /** GroupMemberResponse */
        GroupMemberResponse: {
            /** Display Name */
            display_name: string;
            /** Membership Id */
            membership_id: string;
            /** Person Id */
            person_id: string;
        };
        /** GroupResponse */
        GroupResponse: {
            /** Capacity */
            capacity: number | null;
            capacity_mode: components["schemas"]["GroupCapacityMode"];
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * GuardianAccessStatus
         * @enum {string}
         */
        GuardianAccessStatus: "ACTIVE" | "SUSPENDED" | "REVOKED";
        /** GuardianContactResponse */
        GuardianContactResponse: {
            access_status: components["schemas"]["GuardianAccessStatus"];
            /** Display Name */
            display_name: string;
            /** Guardian Person Id */
            guardian_person_id: string;
            /** Is Primary Contact */
            is_primary_contact: boolean;
            relationship_type: components["schemas"]["GuardianRelationshipType"];
        };
        /**
         * GuardianRelationshipType
         * @enum {string}
         */
        GuardianRelationshipType: "PARENT" | "LEGAL_GUARDIAN" | "OTHER";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LivenessResponse */
        LivenessResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** MeResponse */
        MeResponse: {
            /** Contexts */
            contexts: components["schemas"]["ContextSummary"][];
            /** Display Name */
            display_name: string;
            identity_status: components["schemas"]["PersonIdentityStatus"];
            /** Person Id */
            person_id: string;
        };
        /** MembershipResponse */
        MembershipResponse: {
            /** Admin Note */
            admin_note: string | null;
            /** Id */
            id: string;
            /** Local Member Code */
            local_member_code: string | null;
            /** Person Id */
            person_id: string;
            status: components["schemas"]["MembershipStatus"];
        };
        /**
         * MembershipStatus
         * @enum {string}
         */
        MembershipStatus: "ACTIVE" | "SUSPENDED" | "ENDED";
        /**
         * MembershipTransitionRequest
         * @description Optional operator note explaining an end/suspend/resume.
         */
        MembershipTransitionRequest: {
            /** Reason */
            reason?: string | null;
        };
        /** MergeDecisionRequest */
        MergeDecisionRequest: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "MERGE" | "DISMISS";
            /** Reason */
            reason: string;
        };
        /** MergeReviewResponse */
        MergeReviewResponse: {
            /** Id */
            id: string;
            /** Reason */
            reason: string;
            /** Source Person Id */
            source_person_id: string;
            status: components["schemas"]["PersonMergeStatus"];
            /** Target Person Id */
            target_person_id: string;
        };
        /** OrganizationResponse */
        OrganizationResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string | null;
            /** Timezone */
            timezone: string;
            type: components["schemas"]["OrganizationType"];
        };
        /**
         * OrganizationType
         * @enum {string}
         */
        OrganizationType: "SCHOOL" | "SPORTS_CLUB" | "DANCE_SCHOOL" | "COURSE_PROVIDER" | "EVENT_ORGANIZER" | "BUSINESS" | "OTHER";
        /** Page[ChargeResponse] */
        Page_ChargeResponse_: {
            /** Items */
            items: components["schemas"]["ChargeResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[GroupResponse] */
        Page_GroupResponse_: {
            /** Items */
            items: components["schemas"]["GroupResponse"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[PersonSummary] */
        Page_PersonSummary_: {
            /** Items */
            items: components["schemas"]["PersonSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "CASH" | "BANK_TRANSFER" | "CARD_EXTERNAL" | "OTHER";
        /**
         * PaymentRecordStatus
         * @enum {string}
         */
        PaymentRecordStatus: "RECORDED" | "VOIDED";
        /** PaymentResponse */
        PaymentResponse: {
            /** Amount Minor */
            amount_minor: number;
            /** Charge Amount Due Minor */
            charge_amount_due_minor: number;
            /** Charge Amount Paid Minor */
            charge_amount_paid_minor: number;
            /** Charge Id */
            charge_id: string;
            charge_status: components["schemas"]["ChargeStatus"];
            /** Currency */
            currency: string;
            /** Id */
            id: string;
            method: components["schemas"]["PaymentMethod"];
            status: components["schemas"]["PaymentRecordStatus"];
        };
        /**
         * PersonIdentityStatus
         * @enum {string}
         */
        PersonIdentityStatus: "PROVISIONAL" | "CLAIMED" | "VERIFIED" | "MERGED" | "ARCHIVED";
        /**
         * PersonMergeStatus
         * @description Lifecycle of a duplicate-review case (§13–15).
         *
         *     A case is FLAGGED at intake, then a reviewer either MERGED it (folding the
         *     source into the target) or DISMISSED it (the two are genuinely distinct).
         * @enum {string}
         */
        PersonMergeStatus: "FLAGGED" | "MERGED" | "DISMISSED";
        /** PersonResponse */
        PersonResponse: {
            /** Display Name */
            display_name: string;
            /** Family Name */
            family_name: string;
            /** Given Name */
            given_name: string;
            /** Id */
            id: string;
            identity_status: components["schemas"]["PersonIdentityStatus"];
        };
        /** PersonSummary */
        PersonSummary: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: string;
            identity_status: components["schemas"]["PersonIdentityStatus"];
        };
        /** PostBillingRunRequest */
        PostBillingRunRequest: {
            /** Amount Minor */
            amount_minor: number;
            /** Description */
            description: string;
            /** Group Id */
            group_id: string;
            /** Period Label */
            period_label: string;
            /** Preview Hash */
            preview_hash: string;
        };
        /** PublishAnnouncementRequest */
        PublishAnnouncementRequest: {
            /** Body */
            body: string;
            /** Snapshot Hash */
            snapshot_hash: string;
            /** Target Group Id */
            target_group_id?: string | null;
            target_type: components["schemas"]["AnnouncementTargetType"];
            /** Title */
            title: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Database
             * @enum {string}
             */
            database: "up" | "down";
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "degraded";
        };
        /** RecordPaymentRequest */
        RecordPaymentRequest: {
            /** Amount Minor */
            amount_minor: number;
            method: components["schemas"]["PaymentMethod"];
        };
        /** RegisterChildrenRequest */
        RegisterChildrenRequest: {
            /** Child Person Ids */
            child_person_ids: string[];
        };
        /** RegistrationResponse */
        RegistrationResponse: {
            /** Child Person Id */
            child_person_id: string;
            /** Display Name */
            display_name: string;
            /** Registration Id */
            registration_id: string;
            status: components["schemas"]["RegistrationStatus"];
        };
        /**
         * RegistrationStatus
         * @enum {string}
         */
        RegistrationStatus: "REGISTERED" | "CANCELLED";
        /** RevokeGuardianAccessRequest */
        RevokeGuardianAccessRequest: {
            /** Reason */
            reason?: string | null;
        };
        /**
         * RoleCode
         * @enum {string}
         */
        RoleCode: "OWNER" | "MANAGER" | "ADMIN" | "TRAINER" | "PARENT" | "STUDENT";
        /**
         * RoleScopeType
         * @enum {string}
         */
        RoleScopeType: "ORGANIZATION" | "BRANCH" | "GROUP";
        /** SaveAttendanceRequest */
        SaveAttendanceRequest: {
            /** Attendance Version */
            attendance_version: number;
            /** Exceptions */
            exceptions?: components["schemas"]["AttendanceException"][];
        };
        /** SaveAttendanceResponse */
        SaveAttendanceResponse: {
            /** Absent */
            absent: number;
            /** Attendance Version */
            attendance_version: number;
            /** Excused */
            excused: number;
            /** Late */
            late: number;
            /** Present */
            present: number;
            /** Session Id */
            session_id: string;
        };
        /**
         * SessionDraft
         * @description The proposed shape of a session — used for both conflict preview and create.
         */
        SessionDraft: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Group Id */
            group_id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Title */
            title?: string | null;
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "SCHEDULED" | "CANCELLED" | "COMPLETED";
        /** SessionSummary */
        SessionSummary: {
            /**
             * Ends At
             * Format: date-time
             */
            ends_at: string;
            /** Group Id */
            group_id: string;
            /** Id */
            id: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            status: components["schemas"]["SessionStatus"];
            /** Title */
            title: string | null;
        };
        /**
         * TenantPublic
         * @description Public tenant discovery result — the minimum needed to route a login to
         *     the right school. Reveals no member data.
         */
        TenantPublic: {
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string;
            /** Slug */
            slug: string;
        };
        /**
         * UpdateMemberDataRequest
         * @description School-local member data. Only fields present in the request body are
         *     changed; omit a field to leave it untouched, send ``null`` to clear it.
         */
        UpdateMemberDataRequest: {
            /** Admin Note */
            admin_note?: string | null;
            /** Local Member Code */
            local_member_code?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    googleCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postBillingRun: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostBillingRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingRunResponse"];
                };
            };
            /** @description Preview is stale; review again. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previewBillingRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listCharges: {
        parameters: {
            query?: {
                person_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ChargeResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recordPayment: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                charge_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordPaymentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Overpayment, already settled, or cancelled charge. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publishAnnouncement: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishAnnouncementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementResponse"];
                };
            };
            /** @description Recipient snapshot changed; review again. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    previewAnnouncement: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnnouncementDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnnouncementPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"][];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registerChildren: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterChildrenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"][];
                };
            };
            /** @description Event full or registration closed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancelRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
                registration_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistrationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listGroups: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GroupResponse_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGroupMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    healthReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    createDevIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDevIdentityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevIdentityResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    listMyContexts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextSummary"][];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getCurrentOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
        };
    };
    listMyChildren: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildSummary"][];
                };
            };
        };
    };
    listPeople: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PersonSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createPerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePersonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
            /** @description Possible duplicate; confirm to override. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDuplicatePeople: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCluster"][];
                };
            };
        };
    };
    listMergeReviews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeReviewResponse"][];
                };
            };
        };
    };
    createMergeReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMergeReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decideMergeReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MergeDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeReviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listGuardians: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianContactResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    setPrimaryContact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
                guardian_person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revokeGuardianAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
                guardian_person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeGuardianAccessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianContactResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateMemberData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberDataRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Local member code already used in this org. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Already ended, or last owner of the school. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resumeMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Invalid transition for the current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suspendMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MembershipTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipResponse"];
                };
            };
            /** @description Invalid transition, or last owner of the school. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    checkSessionConflicts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictCheckResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listSchedule: {
        parameters: {
            query: {
                date_from: string;
                date_to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSummary"];
                };
            };
            /** @description Time conflict with an existing session. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getAttendanceSheet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceSheet"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saveAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveAttendanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaveAttendanceResponse"];
                };
            };
            /** @description Attendance changed since it was loaded; reload. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookupTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
